services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:${CLOUDFLARE_VERSION}
    container_name: mangabaka-proxy-cloudflared
    restart: unless-stopped
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN:?copy .env.default file to .env}"
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
